// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ReturnTime struct {
	Server1 *string `json:"server_1"`
	Server2 *string `json:"server_2"`
	Server3 *string `json:"server_3"`
}
